"""Upgrade

Revision ID: 70a7b7b2043e
Revises: bf2bb3d0889f
Create Date: 2023-12-09 12:58:40.066169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a7b7b2043e'
down_revision: Union[str, None] = 'bf2bb3d0889f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
