"""Upgrade

Revision ID: dab8afaac220
Revises: 70a7b7b2043e
Create Date: 2023-12-09 13:05:39.581347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab8afaac220'
down_revision: Union[str, None] = '70a7b7b2043e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_chat_id', table_name='chat')
    op.drop_index('ix_message_id', table_name='message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_message_id', 'message', ['id'], unique=False)
    op.create_index('ix_chat_chat_id', 'chat', ['chat_id'], unique=False)
    # ### end Alembic commands ###
